spring:
  application:
    name: config-server
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"  # Ensure this points to the config server

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0
